# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
window.bindCandidacyCounters = ->
  window.counters = []
  $(".political-candidacy-counter").each (index)->
    counters.push(new window.PoliticalCandidacy($(@)))




$ ->
  modal = document.getElementById('myModal')
  # Get the image and insert it inside the modal - use its "alt" text as a caption
  img = $("#proof-image")
  modalImg = document.getElementById('modal-image')
  captionText = document.getElementById('caption')

  img.click (e)->
    modal.style.display = 'block'
    modalImg.src = @src
    captionText.innerHTML = @alt
    return

  $('.modal-close').click (e)->
    modal.style.display = 'none'
    return

  # ---
  # generated by js2coffee 2.2.0
  
  
  
  resetLoadBar = ->
    $("#step-five-form").find('.progress-bar').attr("aria-valuenow", 0 );
    $("#step-five-form").find('.progress-bar').css("width", "0%" );

  addImage = (data) ->
    $("#proof").html("<img src='#{data.url}' id=\"proof-image\">")
  
  window.bindCandidacyCounters()
  form = $("#step-five-form")
  $("#step-five-form").fileupload
    dataType: 'json'
    fileInput: $('#fileupload-step-five')
    limitMultiFileUploads: 1
    autoUpload: true,
    url: form.attr("action")
    progressall: (e, data) ->
      progress_bar_container = form.find("#progress")
      progress_bar_container.removeClass("d-none")
      progress = parseInt(data.loaded / data.total * 100, 10);
      progress_bar_container.find('.progress-bar').attr("aria-valuenow", progress );
      progress_bar_container.find('.progress-bar').css("width", progress + "%" );
    add: (e, data)->
      data.url = form.attr("action")
      data.process().done -> data.submit()
    done: (e, data) =>
      resetLoadBar()
      if data.result.errors
        if data.result.errors[0] == "Evidences no es válido"
          $.notify("Revise el formáto de la imagen, solo se permiten jpg y png", { globalPosition: "top center" });
        else
          $.notify(data.result.errors.join(", "), { globalPosition: "top center" });
      else
        $("#next-step-wrapper").removeClass("d-none");
        addImage(data.result)
    fail: (e, data) =>
      console.log "form fail"
      resetLoadBar()
      #$.notify("Información guardada", { globalPosition: "top center", className: 'success' });
      $.notify(data.errorThrown + ": " + Object.values(data.messages).join(", "), { globalPosition: "top center" });
    submit: (e, data) ->
      #if !form.canSubmit() then return false
      console.log "form submit"
    send: (e, data) =>
      console.log "form send"
